from typing import Protocol, Any


class StorageBackend(Protocol):
    """Abstract storage protocol. Swap local filesystem for S3/GCS by implementing this."""

    def read(self, path: str) -> dict[str, Any]: ...
    def write(self, path: str, data: dict[str, Any]) -> None: ...
    def list(self, prefix: str) -> list[str]: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
